feature: создан микросервис ewm-db для создания, редактирования, учас…
TrapeznikovDanila/java-explore-with-me pull request #2
Opened 2023-01-02 07:05 UTC by TrapeznikovDanila

…тия и просмотра событий (класс Event), также можно создавать запросы на участие (класс Request), подборки событий (класс Compilation); создан микросервис stats-server для сбора статистики по обращению к публичным эндпоинтам /events и /events/{id}.

2023-01-04 21:47 UTC, sergeymamonov requested changes

2023-01-04 21:47 UTC, sergeymamonov commented on ewm-service/src/main/resources/schema.sql
> +    name VARCHAR NOT NULL,
В скриптах sql размер varchar должен быть ограничен.
Проверить все места использования varchar.

2023-01-04 21:47 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/compilation/CompilationServiceImpl.java
> +        List<Event> events = eventRepository.findAll().stream()
Если нам нужно будет выгрузить несколько событий, а мы выгружаем все и фильтруем на стороне приложения. Если событий миллионы, то по сети будем долго ждать ответ от БД. Лучше попробовать изменить запрос, чтобы БД фильтровала и выдавала только нужные результаты.

2023-01-04 21:47 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/event/EventClient.java
> +    public ResponseEntity<Object> getStats(Timestamp start, Timestamp end, List<String> uris, Boolean unique) {
Используется ли где-то этот метод?

2023-01-04 21:47 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/event/EventService.java
> +    public List<EventShortDto> getEventsFromPublicController(String text, List<Long> categories, Boolean paid, Timestamp rangeStart,
В интерфейсе все методы и так публичные, поэтому модификатор public здесь лишний.

2023-01-04 21:47 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/event/EventServiceImpl.java
> +        } else if ((users == null) && (categories == null) && ((rangeStart != null) && (rangeEnd != null))) {
categories == null - всегда истина. Обращайте внимание на подсказки среды разработки. Смотри также строки 77 и 79.

2023-01-04 21:47 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/event/EventServiceImpl.java
> +            return EventMapper.makeEventFullDto(event);
Строки 198 и 200 идентичны.

2023-01-04 21:47 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/event/Location.java
> +    public Location(String lat, String lon) {
Почему конструктор и геттеры написаны руками, а не через аннотации Lombok?

2023-01-04 21:47 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/exception/ErrorHandler.java
> +//    @ExceptionHandler
В проекте не должно быть закомментированного кода. См. также ниже по классу.

2023-01-04 21:47 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/exception/NotFoundException.java
> +    public NotFoundException(String message) {
Этот конструктор где-то используется? Аналогично для класса ValidationException.

2023-01-04 21:47 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/request/RequestServiceImpl.java
> +//    private final EventRepository repository;
Удалить.

2023-01-04 21:47 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/user/UserServiceImpl.java
> +        List<UserDto> userDtos = repository.findAllByIds(ids2, PageRequest.of(from / size, size))
Не нужно создавать List<UserDto> userDtos, можно сразу вернуть результат вычисления стрима.

2023-01-05 07:36 UTC, TrapeznikovDanila commented on ewm-service/src/main/resources/schema.sql
> +    name VARCHAR NOT NULL,
исправлено

2023-01-05 07:44 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/compilation/CompilationServiceImpl.java
> +        List<Event> events = eventRepository.findAll().stream()
Исправлено

2023-01-05 07:44 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/event/EventClient.java
> +    public ResponseEntity<Object> getStats(Timestamp start, Timestamp end, List<String> uris, Boolean unique) {
Исправлено

2023-01-05 07:45 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/event/EventService.java
> +    public List<EventShortDto> getEventsFromPublicController(String text, List<Long> categories, Boolean paid, Timestamp rangeStart,
Исправлено

2023-01-05 07:47 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/event/EventServiceImpl.java
> +        } else if ((users == null) && (categories == null) && ((rangeStart != null) && (rangeEnd != null))) {
Исправлено

2023-01-05 07:51 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/event/Location.java
> +    public Location(String lat, String lon) {
Исправлено

2023-01-05 07:52 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/exception/ErrorHandler.java
> +//    @ExceptionHandler
Исправлено

2023-01-05 07:52 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/exception/NotFoundException.java
> +    public NotFoundException(String message) {
Исправлено

2023-01-05 07:53 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/request/RequestServiceImpl.java
> +//    private final EventRepository repository;
Исправлено

2023-01-05 07:54 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/user/UserServiceImpl.java
> +        List<UserDto> userDtos = repository.findAllByIds(ids2, PageRequest.of(from / size, size))
Исправлено

2023-01-05 21:20 UTC, sergeymamonov approved these changes

2023-01-05 21:20 UTC, sergeymamonov commented on ewm-service/src/main/resources/schema.sql
> +    location_lat VARCHAR NOT NULL,
В этой строке и в следующей не ограничен размер varchar.

2023-01-05 21:20 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explore_with_me/compilation/CompilationServiceImpl.java
> +                .filter(event -> (compilationDto.getEvents().contains(event.getId()))).collect(Collectors.toList());
Если теперь нужные записи находятся на стороне БД, зачем остались методы .stream и .filter?

2023-01-05 21:20 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/exploreWithMe/event/EventServiceImpl.java
> +            return EventMapper.makeEventFullDto(event);
Обратите внимание, строки в ветках if и else if идентичны.

2023-01-06 10:29 UTC, TrapeznikovDanila commented on ewm-service/src/main/resources/schema.sql
> +    location_lat VARCHAR NOT NULL,
Исправлено

2023-01-06 10:30 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/explore_with_me/compilation/CompilationServiceImpl.java
> +                .filter(event -> (compilationDto.getEvents().contains(event.getId()))).collect(Collectors.toList());
Исправлено

2023-01-06 10:43 UTC, merged