Feature
TrapeznikovDanila/java-explore-with-me pull request #3
Opened 2023-01-08 07:59 UTC by TrapeznikovDanila

Добавлена возможность оставлять, просматривать, редактировать и модерировать комментарии к событиям

2023-01-08 10:56 UTC, DmitrySheyko requested changes
Привет.
Отметил несколько моментов для улучшения. Если будут вопросы пиши.

2023-01-08 10:56 UTC, DmitrySheyko commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/EventServiceImpl.java
> +            UpdatedCommentDto updatedCommentDto = CommentMapper.makeUpdatedCommentDto(comment);
Возможно перед тем как преобразовать comment в Dto и вернуть, его надо сохранить в репозитории.

2023-01-08 10:56 UTC, DmitrySheyko commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/EventServiceImpl.java
> +            return updatedCommentDto;
Я бы удалил UpdatedCommentDto и возвращал бы при обновлении сommentDto. Эти Dto отличаются только наличием даты обновления. При этом, в самой сущности comment у тебя нет поля для сохранения даты обновления. Т.е. эту дату пользователь получит только в момент обновления и далее она потеряется навсегда. Возможно нет смысла делать отдельное Dto для одноразовых данных.

2023-01-08 10:56 UTC, DmitrySheyko commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/EventServiceImpl.java
> +    }
Думаю надо добавить else на случай если comment не найден

2023-01-08 10:56 UTC, DmitrySheyko commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/comment/Comment.java
> +@Data
Обычно Hibernate пишет предупреждение о том, что @Data лучше не использовать т.к. возможны ошибки в работе. Можно заменить на
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor

2023-01-08 10:56 UTC, DmitrySheyko commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/EventMapper.java
> +            eventFullDto.setComments(event.getComments().stream()
Насколько я помню, у тебя в коде нигде нет записи комментов в event. Ты их записываешь в EventFullDto. Возможно, что эта строчка, а также поле comments  в сущности event не нужны.

2023-01-08 10:56 UTC, DmitrySheyko commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/EventPrivateController.java
> +                                     @RequestBody @Validated NewCommentDto commentDto) {
Здесь @Validated можно заменить на @Valid  и убрать @Validated перед названием класса.

2023-01-08 10:56 UTC, DmitrySheyko commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/comment/Comment.java
> +    private long userId;
Т.е. названия полей в сущности не полностью совпадают с названиями полей в таблице comments, рекомендую добавить аннотации @Column(name="user_id").
И так далее для всех полей.

2023-01-08 10:56 UTC, DmitrySheyko commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/comment/CommentRepository.java
> +}
Как я понял получить из репозитория можно только комменты в статусе PUBLISHED.
Рекомендую добавить еще какой-нибудь способ получения комментов, чтобы можно было получить отклонённые модератором комменты. Автору комментов это может быть полезно.

2023-01-10 02:52 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/EventServiceImpl.java
> +            UpdatedCommentDto updatedCommentDto = CommentMapper.makeUpdatedCommentDto(comment);
Согласен. Упустил этот момент, спасибо.

2023-01-10 02:53 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/EventServiceImpl.java
> +            return updatedCommentDto;
Да, согласен, удалили UpdatedCommentDto, добавил поле updated в entity и dto, создал соответствующую графу в бд

2023-01-10 02:55 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/EventServiceImpl.java
> +    }
Согласен, добавил.

2023-01-10 02:59 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/comment/Comment.java
> +@Data
Да, я понимаю, спасибо. Но в проекте все сущности с @Data, если вносить изменения, то во всем проекте. Учту на будущее.

2023-01-10 03:02 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/EventMapper.java
> +            eventFullDto.setComments(event.getComments().stream()
Как раз записываю комментарии в entity и маплю потом в dto.

2023-01-10 03:12 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/EventPrivateController.java
> +                                     @RequestBody @Validated NewCommentDto commentDto) {
Заменил. Насколько я понимаю, @Valid не отрабатывает когда валидируются группы объектов, то есть если в теле запроса не List<?> то смысла в @Validated нет? Если Виктор увидит этот комментарий, прошу его пролить свет, т.к. из документации до конца не понял

2023-01-10 03:15 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/comment/Comment.java
> +    private long userId;
Спасибо. но считаю лишним, фреймворк справляется, если соблюдены правила названия полей в бд и CamelCase в entity

2023-01-10 10:14 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/comment/CommentRepository.java
> +}
Добавил 2 эндпоинта для получения комментариев: 1 для админа, 1 для зарегистрированных пользователей.

2023-01-10 11:08 UTC, victorspring commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/comment/Comment.java
> +    private long id;
Примитивные типы для айдишников плохая практика https://stackoverflow.com/questions/3535791/primitive-or-wrapper-for-hibernate-primary-keys

2023-01-10 11:08 UTC, victorspring commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/comment/Comment.java
> +    private long eventId;
Почему просто eventId, а не ссылка на сущность - Event event?

2023-01-10 11:08 UTC, victorspring commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/comment/dto/CommentDto.java
> +    private long id;
В дто лучше тоже сделать nullable тип данных для айди, т.е. Long

2023-01-10 11:08 UTC, victorspring commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/comment/dto/UpdateCommentRequest.java
> +    private long id;
И тут Long

2023-01-10 11:08 UTC, victorspring commented on ewm-service/src/main/resources/schema.sql
> +    CONSTRAINT pk_comments PRIMARY KEY (id)
Констрейты можно удобнее добавлять прямо при объявлении колонки https://www.w3schools.com/sql/sql_primarykey.ASP

2023-01-10 11:19 UTC, DmitrySheyko approved these changes

2023-01-11 00:41 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/comment/Comment.java
> +    private long id;
Исправил во всем проекте

2023-01-11 00:42 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/comment/dto/CommentDto.java
> +    private long id;
Исправил во всем проекте

2023-01-11 00:51 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/comment/Comment.java
> +    private long eventId;
Исправил, но не понимаю, почему в моем случае это лучше, ведь в составе CommentDto я отправляю только eventId и userId

2023-01-11 00:51 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/comment/dto/UpdateCommentRequest.java
> +    private long id;
Исправил во всем проекте

2023-01-11 01:01 UTC, TrapeznikovDanila commented on ewm-service/src/main/resources/schema.sql
> +    CONSTRAINT pk_comments PRIMARY KEY (id)
Исправил везде, кроме составных PK

2023-01-11 01:04 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/comment/dto/UpdateCommentRequest.java
> +    private long id;
Исправлено во всем проекте

2023-01-11 01:05 UTC, TrapeznikovDanila commented on ewm-service/src/main/java/ru/practicum/explore_with_me/event/comment/dto/CommentDto.java
> +    private long id;
Исправлено во всем проекте

2023-01-19 04:21 UTC, closed without merging